version: "2"
services:
  lunchrooms-ms:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - lunchrooms-db
    command: bin/lunchrooms-ms    
  lunchrooms-db:
    image: mongo:latest
    ports:
      - "27017:27017"
